import "./globals.css";
import { ThemeProvider } from "@/components/ui/theme-provider";
import { BottomNav } from "./components/BottomNavbar";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          {children}
          <BottomNav />
        </ThemeProvider>
      </body>
    </html>
  );
}
