# Main config file
# Define things like DB name, ports, JWT expiry, etc.
# remember to put all the fields
database:
  host: "localhost"
  name: "compass"
  user: "postgres"

  port: 5432

rabbitmq:
  host: "localhost"
  user: "guest"
  password: "guest"
  mailqueue: "mail_queue" # Keep the names consistent <type>queue for protect the publish logic correct
  moderationqueue: "moderation_queue"
  port: 5672

ports:
  auth: 8080
  maps: 8081
  assets: 8082

smtp:
  host: smtp.gmail.com
  port: 587

domain: localhost

expiry:
  emailVerification: 3

# TODO: Understand how can we change the configs in run time
image:
  quality: 40

noticeboard:
  limit: 5
